export type Lang = "uz" | "ru" | "en";

export const SUPPORTED_LANGS: Lang[] = ["uz", "ru", "en"];

export const copy = {
  uz: {
    meta: {
      title: "Yuristim — O‘zbekiston uchun LegalTech",
      description: "AI yuridik yordam, huquqiy hujjatlar va professional yuristlarni yagona platformada birlashtiruvchi O‘zbekiston LegalTech ekotizimi.",
    },
    nav: {
      about: "Biz haqimizda",
      capabilities: "Imkoniyatlar",
      how: "Qanday ishlaydi",
      ecosystem: "Ekotizim",
      future: "Kelajagimiz",
      team: "Jamoa",
      contact: "Aloqa",
      open: "Yuristimni ochish",
      menu: "Menyu",
      close: "Yopish",
    },
    hero: {
      eyebrow: "O‘ZBEKISTON UCHUN LEGALTECH",
      title: "Huquqiy masalani qayerdan boshlash endi aniqroq.",
      body: "Muammoingizni yozing. Yuristim vaziyatni tushunishga, keyingi huquqiy qadamlarni aniqlashga va kerak bo‘lsa hujjat yoki professional yuristga o‘tishga yordam beradi.",
      primary: "Yuristimni ochish",
      secondary: "Telegram bot",
      tertiary: "Birinchi qabul",
      problem: "HUQUQIY MUAMMO",
      ai: "AI YORDAM",
      document: "HUJJAT",
      lawyer: "YURIST",
      workspace: "LEGAL WORKSPACE",
    },
    trust: [
      "O‘zbekiston huquqiga yo‘naltirilgan",
      "Web + Telegram + Mini App",
      "AI + professional yuristlar",
      "UZ · RU · EN",
    ],
    problem: {
      eyebrow: "MUAMMO",
      title: "Huquqiy muammo paydo bo‘lganda eng qiyin savol — qayerdan boshlash?",
      body: "Huquqiy yordamga ehtiyoj ko‘pincha bitta savol bilan boshlanadi. Keyingi yo‘l esa tezda bo‘laklarga ajralib ketadi.",
      steps: [
        ["01", "Muammo yuzaga keladi", "Vaziyat bor, lekin uni huquqiy tilda qanday ifodalash noaniq."],
        ["02", "Ma’lumot tarqoq", "Qonun, izoh, tajriba va maslahatlar turli joylarda qolib ketadi."],
        ["03", "Hujjat masalasi", "Qaysi ariza, talab yoki shartnoma kerakligini aniqlash oson emas."],
        ["04", "Yurist tanlash", "Qaysi mutaxassisga murojaat qilish va qayerdan topish savoli qoladi."],
      ],
      resolution: "Yuristim bu bosqichlarni bitta izchil legal workspace ichida bog‘lash uchun qurilmoqda.",
    },
    about: {
      eyebrow: "BIZ HAQIMIZDA",
      title: "Chatbot emas. Huquqiy ish jarayoni uchun yagona muhit.",
      body: "Yuristim AI yordam, hujjatlar, professional yuristlar va huquqiy bilimni bitta identifikatsiya va bitta tajriba ichida birlashtiruvchi LegalTech ekotizim sifatida rivojlantirilmoqda.",
      tags: ["AI yordam", "Hujjatlar", "Professional yuristlar", "Huquqiy bilim"],
    },
    pillars: {
      eyebrow: "UCHTA ASOSIY YO‘NALISH",
      title: "Savoldan keyingi qadamgacha.",
      items: [
        {
          number: "01",
          title: "AI huquqiy yordam",
          body: "Vaziyatni oddiy tilda yozing. Yuristim huquqiy kontekstni tartiblaydi va keyingi qadamlarni tushunarli shaklda ko‘rsatadi.",
          label: "Savol → tahlil → yo‘nalish",
        },
        {
          number: "02",
          title: "Professional yuristlar",
          body: "Murojaatingizni tasdiqlangan yuristlar qabul qilishi mumkin. Nomzodlar orasidan yakuniy tanlovni foydalanuvchi qiladi.",
          label: "Murojaat → nomzodlar → tanlov",
        },
        {
          number: "03",
          title: "Hujjatlar",
          body: "Tayyor namunalar va alohida ishlab chiqilayotgan AI hujjat generatori bir xil narsa emas. Sifat va tekshiruv birinchi o‘rinda.",
          label: "Namuna ≠ generator",
        },
      ],
    },
    ai: {
      eyebrow: "AI REJIMLARI",
      title: "Tez savol uchun ham, murakkab tahlil uchun ham bitta interfeys.",
      description: "Foydalanuvchiga model nomlari emas, vazifaga mos rejimlar ko‘rsatiladi.",
      fast: {
        name: "TEZKOR",
        title: "Kundalik huquqiy savollar",
        body: "Qisqa savollar, dastlabki yo‘nalish va keyingi qadamni tez tushunish uchun.",
        bullets: ["Tez javob", "Oddiy tilda", "Kundalik vaziyatlar"],
      },
      expert: {
        name: "EKSPERT",
        title: "Murakkabroq huquqiy tahlil",
        body: "Ko‘proq kontekst, ehtiyotkor tahlil va strukturali yondashuv talab qiladigan vaziyatlar uchun.",
        bullets: ["Ko‘proq kontekst", "Strukturali tahlil", "Murakkab vaziyatlar"],
      },
    },
    how: {
      eyebrow: "QANDAY ISHLAYDI",
      title: "Bir savoldan amaliy keyingi qadamgacha.",
      steps: [
        ["01", "Muammoingizni yozing", "Vaziyatni sizga qulay tilda tushuntiring."],
        ["02", "Yuristim vaziyatni tushunadi", "Huquqiy kontekst va asosiy masalalar ajratiladi."],
        ["03", "Keyingi qadamlarni ko‘ring", "Nima qilish mumkinligi tushunarli ketma-ketlikda beriladi."],
        ["04", "Kerak bo‘lsa hujjat yoki yuristga o‘ting", "Bitta ekotizim ichida keyingi vositaga o‘tasiz."],
      ],
    },
    marketplace: {
      eyebrow: "YURISTLAR MARKETPLACE",
      title: "Tasodifiy katalog emas — murojaatdan tanlovgacha boshqariladigan oqim.",
      body: "Murojaat ochiladi, talabga mos tasdiqlangan yuristlar uni qabul qiladi, siz nomzodlarni ko‘rasiz va yuristni o‘zingiz tanlaysiz.",
      flow: ["Murojaat", "Verified yuristlar", "Nomzodlar", "Siz tanlaysiz", "Baho"],
      cta: "Yuristlar sahifasi",
      note: "Yakuniy huquqiy natija kafolatlanmaydi; platforma aloqa va tanlov jarayonini tashkil qiladi.",
    },
    documents: {
      eyebrow: "HUJJATLAR",
      title: "Namuna va AI generator — ikki xil mahsulot qatlami.",
      sampleTitle: "Hujjat namunalari",
      sampleBody: "Tayyor huquqiy hujjat namunalari alohida kutubxonada joylashadi.",
      betaTitle: "Yuristim Hujjat · Beta",
      betaBody: "Generator yo‘nalishi real misollar, research, strukturali template va testlar asosida bosqichma-bosqich ishlab chiqilmoqda.",
      sampleCta: "Namunalarni ko‘rish",
      betaCta: "Hujjat Beta",
      process: ["Real misollar", "Research", "Strukturali template", "Testing", "Stable generator"],
    },
    ecosystem: {
      eyebrow: "YAGONA EKOTIZIM",
      title: "Bitta Yuristim. Turli huquqiy vositalar.",
      body: "Web, Mini App, Telegram Bot, yuristlar, adabiyot va hujjatlar alohida startup emas — bitta identifikatsiya atrofidagi yagona legal ecosystem.",
      center: "YURISTIM",
    },
    roadmap: {
      eyebrow: "BUGUN → KELAJAK",
      title: "Yuristim qayerga ketyapti?",
      today: "BUGUN",
      future: "KELAJAK",
      todayItems: ["AI savol-javob", "Account", "Telegram Bot", "Yurist topish", "Credits"],
      futureItems: ["Rasmiy huquqiy manbalar", "Legal knowledge", "Document workspace", "Advanced document generation", "Professional marketplace", "Unified legal workspace"],
      note: "Kelajak qismi — mahsulot yo‘nalishi. U yerdagi imkoniyatlar hozir tayyor deb taqdim etilmaydi.",
    },
    team: {
      eyebrow: "JAMOA",
      title: "Mahsulot ortida odam bor.",
      founderLabel: "FOUNDER",
      founderName: "Ne’matov Diyorbek Dilshidjon o‘g‘li",
      founderRole: "Founder / Product Lead",
      founderBio: "Yuristim g‘oyasi huquqiy yordamga kirishni soddalashtirish va O‘zbekiston uchun zamonaviy LegalTech ekotizimini qurish maqsadidan kelib chiqqan. Fokus — texnologiyani huquqiy jarayonning o‘rniga qo‘yish emas, balki uni tushunarliroq va bog‘langan qilish.",
      founderAlt: "Yuristim founder Ne’matov Diyorbek portreti",
    },
    admission: {
      eyebrow: "BIRINCHI QABUL",
      title: "Yuristimning birinchi foydalanuvchilaridan biri bo‘ling.",
      body: "Demo va ilk foydalanish tajribasini sinab ko‘rish uchun Birinchi qabul sahifasiga o‘ting.",
      cta: "Birinchi qabulga o‘tish",
    },
    trustSection: {
      eyebrow: "ISHONCH VA NAZORAT",
      title: "Tushunarli identifikatsiya. Ochiq qoidalar. Tekshirilgan oqimlar.",
      items: [
        ["Telegram-backed account", "Kirish va identifikatsiya Telegram bilan bog‘langan foydalanuvchi oqimiga tayangan."],
        ["DUID identity", "Platforma ichidagi maxsus identifikator foydalanuvchi tajribasini birlashtirishga xizmat qiladi."],
        ["Privacy-conscious sessions", "Sessiya va kirish oqimlari ortiqcha shaxsiy ma’lumotni oshkor qilmaslik tamoyili bilan quriladi."],
        ["Verified lawyer profiles", "Marketplace oqimida tasdiqlangan yurist profillari alohida tekshiruv bosqichiga ega."],
      ],
      offer: "Ommaviy oferta",
    },
    final: {
      eyebrow: "BOSHLASH UCHUN",
      title: "Huquqiy savolingizni yozing.",
      body: "Bitta savol bilan boshlang. Keyingi yo‘lni Yuristim ichida ko‘ring.",
      primary: "Yuristimni ochish",
      secondary: "Telegram orqali boshlash",
    },
    footer: {
      summary: "O‘zbekiston uchun AI, hujjatlar va professional yuristlarni bog‘lovchi LegalTech ekotizimi.",
      product: "Mahsulot",
      company: "Yuristim",
      legal: "Huquqiy",
      web: "Web",
      lawyers: "Yuristlar",
      literature: "Adabiyot",
      samples: "Namunalar",
      documentBeta: "Hujjat Beta",
      about: "Biz haqimizda",
      team: "Jamoa",
      future: "Kelajagimiz",
      telegram: "Telegram",
      miniApp: "Mini App",
      offer: "Ommaviy oferta",
      rights: "Yuristim. Barcha huquqlar himoyalangan.",
    },
  },
  ru: {
    meta: {
      title: "Yuristim — LegalTech для Узбекистана",
      description: "LegalTech-экосистема Узбекистана, объединяющая юридическую AI-помощь, документы и профессиональных юристов на одной платформе.",
    },
    nav: {
      about: "О нас",
      capabilities: "Возможности",
      how: "Как работает",
      ecosystem: "Экосистема",
      future: "Будущее",
      team: "Команда",
      contact: "Контакты",
      open: "Открыть Yuristim",
      menu: "Меню",
      close: "Закрыть",
    },
    hero: {
      eyebrow: "LEGALTECH ДЛЯ УЗБЕКИСТАНА",
      title: "Теперь понятнее, с чего начать решение юридического вопроса.",
      body: "Опишите ситуацию. Yuristim помогает понять правовой контекст, определить следующие шаги и при необходимости перейти к документу или профессиональному юристу.",
      primary: "Открыть Yuristim",
      secondary: "Telegram-бот",
      tertiary: "Первый приём",
      problem: "ЮРИДИЧЕСКАЯ ПРОБЛЕМА",
      ai: "AI-ПОМОЩЬ",
      document: "ДОКУМЕНТ",
      lawyer: "ЮРИСТ",
      workspace: "LEGAL WORKSPACE",
    },
    trust: ["Ориентировано на право Узбекистана", "Web + Telegram + Mini App", "AI + профессиональные юристы", "UZ · RU · EN"],
    problem: {
      eyebrow: "ПРОБЛЕМА",
      title: "Когда возникает правовой вопрос, самое сложное — понять, с чего начать.",
      body: "Потребность в юридической помощи часто начинается с одного вопроса, но дальнейший путь быстро распадается на части.",
      steps: [
        ["01", "Возникает проблема", "Ситуация понятна по фактам, но неясно, как сформулировать её юридически."],
        ["02", "Информация разбросана", "Нормы, пояснения, практика и советы находятся в разных местах."],
        ["03", "Неясен документ", "Нужно понять, требуется ли заявление, требование, иск или договор."],
        ["04", "Выбор юриста", "Остаётся вопрос, к какому специалисту обратиться и где его найти."],
      ],
      resolution: "Yuristim создаётся, чтобы связать эти этапы в одном последовательном legal workspace.",
    },
    about: {
      eyebrow: "О YURISTIM",
      title: "Не только чат-бот. Единая среда для юридических задач.",
      body: "Yuristim развивается как LegalTech-экосистема, объединяющая AI-помощь, документы, профессиональных юристов и юридические знания в одном продукте.",
      tags: ["AI-помощь", "Документы", "Профессиональные юристы", "Юридические знания"],
    },
    pillars: {
      eyebrow: "ТРИ ОСНОВНЫХ НАПРАВЛЕНИЯ",
      title: "От вопроса к следующему практическому шагу.",
      items: [
        { number: "01", title: "AI юридическая помощь", body: "Опишите ситуацию обычным языком. Yuristim структурирует правовой контекст и показывает следующие шаги понятным способом.", label: "Вопрос → анализ → направление" },
        { number: "02", title: "Профессиональные юристы", body: "Подтверждённые юристы могут принять ваше обращение. Вы просматриваете кандидатов и выбираете специалиста самостоятельно.", label: "Обращение → кандидаты → выбор" },
        { number: "03", title: "Документы", body: "Готовые образцы и AI-генератор документов — разные слои продукта. Качество и тестирование важнее преждевременных обещаний.", label: "Образец ≠ генератор" },
      ],
    },
    ai: {
      eyebrow: "AI-РЕЖИМЫ",
      title: "Один интерфейс для быстрых вопросов и более глубокого анализа.",
      description: "Пользователь видит режимы по задаче, а не названия внутренних провайдеров.",
      fast: { name: "БЫСТРО", title: "Повседневные правовые вопросы", body: "Для коротких вопросов, первичной ориентации и быстрого понимания следующего шага.", bullets: ["Быстрый ответ", "Понятный язык", "Повседневные ситуации"] },
      expert: { name: "ЭКСПЕРТ", title: "Более сложный правовой анализ", body: "Для ситуаций, где нужен больший контекст, осторожный анализ и структурированный подход.", bullets: ["Больше контекста", "Структурированный анализ", "Сложные ситуации"] },
    },
    how: {
      eyebrow: "КАК ЭТО РАБОТАЕТ",
      title: "От одного вопроса к практическому следующему шагу.",
      steps: [
        ["01", "Опишите проблему", "Расскажите о ситуации удобным для вас языком."],
        ["02", "Yuristim понимает контекст", "Выделяются правовая рамка и ключевые вопросы."],
        ["03", "Посмотрите следующие шаги", "Возможные действия показываются в понятной последовательности."],
        ["04", "При необходимости перейдите к документу или юристу", "Продолжите работу следующим инструментом в той же экосистеме."],
      ],
    },
    marketplace: {
      eyebrow: "MARKETPLACE ЮРИСТОВ",
      title: "Не случайный каталог — управляемый путь от обращения до выбора.",
      body: "Вы создаёте обращение, подходящие подтверждённые юристы могут его принять, после чего вы сами выбираете из кандидатов.",
      flow: ["Обращение", "Проверенные юристы", "Кандидаты", "Вы выбираете", "Оценка"],
      cta: "Страница юристов",
      note: "Правовой результат не гарантируется; платформа организует поиск, контакт и выбор.",
    },
    documents: {
      eyebrow: "ДОКУМЕНТЫ",
      title: "Образцы документов и AI-генератор — два разных слоя продукта.",
      sampleTitle: "Образцы документов",
      sampleBody: "Готовые примеры юридических документов размещаются в отдельной библиотеке.",
      betaTitle: "Yuristim Hujjat · Beta",
      betaBody: "Направление генератора поэтапно развивается на основе реальных примеров, research, структурированных шаблонов и тестирования.",
      sampleCta: "Смотреть образцы",
      betaCta: "Hujjat Beta",
      process: ["Реальные примеры", "Research", "Структурный шаблон", "Testing", "Stable generator"],
    },
    ecosystem: {
      eyebrow: "ЕДИНАЯ ЭКОСИСТЕМА",
      title: "Один Yuristim. Разные юридические инструменты.",
      body: "Web, Mini App, Telegram Bot, юристы, литература и документы — не отдельные стартапы, а одна legal ecosystem вокруг общей идентичности.",
      center: "YURISTIM",
    },
    roadmap: {
      eyebrow: "СЕГОДНЯ → БУДУЩЕЕ",
      title: "Куда движется Yuristim?",
      today: "СЕГОДНЯ",
      future: "БУДУЩЕЕ",
      todayItems: ["AI вопросы и ответы", "Account", "Telegram Bot", "Поиск юриста", "Credits"],
      futureItems: ["Официальные правовые источники", "Legal knowledge", "Document workspace", "Advanced document generation", "Professional marketplace", "Unified legal workspace"],
      note: "Колонка будущего описывает направление продукта и не представляется как уже выпущенный функционал.",
    },
    team: {
      eyebrow: "КОМАНДА",
      title: "За продуктом стоит человек.",
      founderLabel: "FOUNDER",
      founderName: "Ne’matov Diyorbek Dilshidjon o‘g‘li",
      founderRole: "Founder / Product Lead",
      founderBio: "Yuristim появился из цели упростить доступ к юридической помощи и построить современную LegalTech-экосистему для Узбекистана. Технология здесь не заменяет юридическую работу, а делает путь понятнее и связаннее.",
      founderAlt: "Портрет основателя Yuristim Ne’matov Diyorbek",
    },
    admission: {
      eyebrow: "ПЕРВЫЙ ПРИЁМ",
      title: "Станьте одним из первых пользователей Yuristim.",
      body: "Перейдите на страницу Первого приёма, чтобы попробовать демо и ранний продуктовый опыт.",
      cta: "Открыть Первый приём",
    },
    trustSection: {
      eyebrow: "ДОВЕРИЕ И КОНТРОЛЬ",
      title: "Понятная идентификация. Открытые правила. Проверенные процессы.",
      items: [
        ["Telegram-backed account", "Вход и идентификация связаны с пользовательским потоком через Telegram."],
        ["DUID identity", "Специальный идентификатор помогает объединять пользовательский опыт внутри Yuristim."],
        ["Privacy-conscious sessions", "Сессионные процессы строятся с учётом минимального раскрытия лишних персональных данных."],
        ["Verified lawyer profiles", "Профили юристов в marketplace проходят отдельный этап подтверждения."],
      ],
      offer: "Публичная оферта",
    },
    final: {
      eyebrow: "НАЧАТЬ",
      title: "Опишите свой юридический вопрос.",
      body: "Начните с одного вопроса и увидьте следующий путь внутри Yuristim.",
      primary: "Открыть Yuristim",
      secondary: "Начать в Telegram",
    },
    footer: {
      summary: "LegalTech-экосистема Узбекистана, объединяющая AI, документы и профессиональных юристов.",
      product: "Продукт",
      company: "Yuristim",
      legal: "Правовое",
      web: "Web",
      lawyers: "Юристы",
      literature: "Литература",
      samples: "Образцы",
      documentBeta: "Hujjat Beta",
      about: "О нас",
      team: "Команда",
      future: "Будущее",
      telegram: "Telegram",
      miniApp: "Mini App",
      offer: "Публичная оферта",
      rights: "Yuristim. Все права защищены.",
    },
  },
  en: {
    meta: {
      title: "Yuristim — LegalTech for Uzbekistan",
      description: "A LegalTech ecosystem for Uzbekistan bringing AI legal assistance, legal documents and professional lawyers into one platform.",
    },
    nav: {
      about: "About",
      capabilities: "Capabilities",
      how: "How it works",
      ecosystem: "Ecosystem",
      future: "Future",
      team: "Team",
      contact: "Contact",
      open: "Open Yuristim",
      menu: "Menu",
      close: "Close",
    },
    hero: {
      eyebrow: "LEGALTECH FOR UZBEKISTAN",
      title: "A clearer place to start with a legal issue.",
      body: "Describe the situation. Yuristim helps you understand the legal context, identify next steps and, when needed, move to a document or a professional lawyer.",
      primary: "Open Yuristim",
      secondary: "Telegram bot",
      tertiary: "First Admission",
      problem: "LEGAL ISSUE",
      ai: "AI HELP",
      document: "DOCUMENT",
      lawyer: "LAWYER",
      workspace: "LEGAL WORKSPACE",
    },
    trust: ["Built around Uzbekistan law", "Web + Telegram + Mini App", "AI + professional lawyers", "UZ · RU · EN"],
    problem: {
      eyebrow: "THE PROBLEM",
      title: "When a legal issue appears, the hardest question is often: where do I start?",
      body: "The need for legal help may begin with one question, but the next steps quickly become fragmented.",
      steps: [
        ["01", "A problem appears", "You know what happened, but not how to frame it in legal terms."],
        ["02", "Information is scattered", "Rules, explanations, practice and advice live in different places."],
        ["03", "The document is unclear", "It is not obvious whether you need a claim, request, application or contract."],
        ["04", "Choosing a lawyer", "You still need to know which specialist to approach and where to find one."],
      ],
      resolution: "Yuristim is being built to connect these stages inside one coherent legal workspace.",
    },
    about: {
      eyebrow: "ABOUT YURISTIM",
      title: "Not only a chatbot. A connected workspace for legal tasks.",
      body: "Yuristim is being developed as a LegalTech ecosystem that brings AI assistance, documents, professional lawyers and legal knowledge into one identity and one product experience.",
      tags: ["AI assistance", "Documents", "Professional lawyers", "Legal knowledge"],
    },
    pillars: {
      eyebrow: "THREE CORE DIRECTIONS",
      title: "From a question to the next practical step.",
      items: [
        { number: "01", title: "AI legal assistance", body: "Describe the situation in plain language. Yuristim structures the legal context and presents the next steps clearly.", label: "Question → analysis → direction" },
        { number: "02", title: "Professional lawyers", body: "Verified lawyers may accept your request. You review the candidates and make the final choice yourself.", label: "Request → candidates → choice" },
        { number: "03", title: "Documents", body: "Ready-made samples and an AI document generator are different product layers. Yuristim prioritizes quality and testing over premature claims.", label: "Sample ≠ generator" },
      ],
    },
    ai: {
      eyebrow: "AI MODES",
      title: "One interface for quick questions and deeper analysis.",
      description: "The product shows task-oriented modes rather than underlying provider names.",
      fast: { name: "FAST", title: "Everyday legal guidance", body: "For short questions, initial orientation and a quick understanding of what to do next.", bullets: ["Fast response", "Plain language", "Everyday situations"] },
      expert: { name: "EXPERT", title: "More complex legal analysis", body: "For situations that need more context, careful analysis and a structured approach.", bullets: ["More context", "Structured analysis", "Complex situations"] },
    },
    how: {
      eyebrow: "HOW IT WORKS",
      title: "From one question to a practical next step.",
      steps: [
        ["01", "Describe your problem", "Explain the situation in the language that is easiest for you."],
        ["02", "Yuristim understands the context", "The legal frame and key issues are separated."],
        ["03", "See the next steps", "Possible actions are shown in a clear sequence."],
        ["04", "Move to a document or lawyer when needed", "Continue with the next tool inside the same ecosystem."],
      ],
    },
    marketplace: {
      eyebrow: "LAWYER MARKETPLACE",
      title: "Not a random directory — a managed flow from request to choice.",
      body: "Create a request, eligible verified lawyers can accept it, you review the candidates and choose the lawyer yourself.",
      flow: ["Request", "Verified lawyers", "Candidates", "You choose", "Review"],
      cta: "Lawyers surface",
      note: "Legal outcomes are not guaranteed; the platform organizes discovery, contact and selection.",
    },
    documents: {
      eyebrow: "DOCUMENTS",
      title: "Document samples and an AI generator are two different product layers.",
      sampleTitle: "Document samples",
      sampleBody: "Ready legal document examples live in a dedicated library.",
      betaTitle: "Yuristim Hujjat · Beta",
      betaBody: "The generator direction is being developed step by step around real examples, research, structured templates and testing.",
      sampleCta: "View samples",
      betaCta: "Hujjat Beta",
      process: ["Real examples", "Research", "Structured template", "Testing", "Stable generator"],
    },
    ecosystem: {
      eyebrow: "ONE ECOSYSTEM",
      title: "One Yuristim. Different legal tools.",
      body: "Web, Mini App, Telegram Bot, lawyers, literature and documents are not separate startups — they are one legal ecosystem around a shared identity.",
      center: "YURISTIM",
    },
    roadmap: {
      eyebrow: "TODAY → FUTURE",
      title: "Where is Yuristim going?",
      today: "TODAY",
      future: "FUTURE",
      todayItems: ["AI Q&A", "Account", "Telegram Bot", "Find a lawyer", "Credits"],
      futureItems: ["Official legal sources", "Legal knowledge", "Document workspace", "Advanced document generation", "Professional marketplace", "Unified legal workspace"],
      note: "The future column describes product direction. It is not presented as already shipped functionality.",
    },
    team: {
      eyebrow: "TEAM",
      title: "There is a person behind the product.",
      founderLabel: "FOUNDER",
      founderName: "Ne’matov Diyorbek Dilshidjon o‘g‘li",
      founderRole: "Founder / Product Lead",
      founderBio: "Yuristim started from the goal of making access to legal help simpler and building a modern LegalTech ecosystem for Uzbekistan. The focus is not to replace legal work with technology, but to make the path more understandable and connected.",
      founderAlt: "Portrait of Yuristim founder Ne’matov Diyorbek",
    },
    admission: {
      eyebrow: "FIRST ADMISSION",
      title: "Become one of Yuristim’s first users.",
      body: "Visit the First Admission page to explore the demo and early product experience.",
      cta: "Open First Admission",
    },
    trustSection: {
      eyebrow: "TRUST & CONTROL",
      title: "Clear identity. Public terms. Verified flows.",
      items: [
        ["Telegram-backed account", "Sign-in and identity are connected to a Telegram-backed user flow."],
        ["DUID identity", "A dedicated in-product identifier helps connect the user experience across Yuristim."],
        ["Privacy-conscious sessions", "Session flows are designed around minimizing unnecessary exposure of personal data."],
        ["Verified lawyer profiles", "Lawyer marketplace profiles have a dedicated verification step."],
      ],
      offer: "Public offer",
    },
    final: {
      eyebrow: "START HERE",
      title: "Write your legal question.",
      body: "Start with one question, then follow the next step inside Yuristim.",
      primary: "Open Yuristim",
      secondary: "Start in Telegram",
    },
    footer: {
      summary: "A LegalTech ecosystem for Uzbekistan connecting AI, documents and professional lawyers.",
      product: "Product",
      company: "Yuristim",
      legal: "Legal",
      web: "Web",
      lawyers: "Lawyers",
      literature: "Literature",
      samples: "Samples",
      documentBeta: "Hujjat Beta",
      about: "About",
      team: "Team",
      future: "Future",
      telegram: "Telegram",
      miniApp: "Mini App",
      offer: "Public offer",
      rights: "Yuristim. All rights reserved.",
    },
  },
} as const;

export type SiteCopy = (typeof copy)[Lang];
